### ISSUE TITLE
Antique Mall results for 'kearney'"

### ISSUE THREAD

**Issue by katiebritt** [vintage-software/arbor#9] opened 2017-04-25 16:24 UTC
![Screen Shot 2017-04-25 at 4:24 PM](http://marker.screenshots.prod.s3.amazonaws.com/2dba94e6f9174407aaedeb7aaa805c47-1493137450093.png)
---
### More Info

**Source URL**: [https://www.antiquemalls.com/search?SearchTerm=kearney](https://www.antiquemalls.com/search?SearchTerm=kearney)

<table><tr><td><strong>Browser</strong></td><td>Chrome 57.0.2987.133</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1936 x 1056</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</td></tr></table>

**Comment by kevinphelps** [comment] 2017-05-23 07:13
This is intended behavior. It's showing the metro area result even though there are no malls. Estate Sales does the same thing. https://www.estatesales.net/search/Kearney

**Comment by kevinphelps** [comment] 2017-05-23 07:15
![screenshot_2017-05-23-02-15-06](https://cloud.githubusercontent.com/assets/7399499/26342445/b86091a2-3f5d-11e7-9622-0bb973d090d4.png)

https://www.estatesales.net/search/Kearney

**Comment by kevinphelps** [comment] 2017-06-08 19:17
I just realized this issue is opened in the wrong repo anyway. Closing...

**Closed by kevinphelps** 2017-06-08 19:17 UTC
